Repository tanamoe/azunyan, pull requests merged in 2023-05, with the labels that each got.

#4 fix(deps): patched ytdl-core not installing properly
  package.json
  pnpm-lock.yaml
Labels: bug

#5 feat: implement logger using pino
  package.json
  pnpm-lock.yaml
  src/commands/player/youtube.ts
  src/lib/logger.ts
  tsconfig.json
Labels: enhancement

#7 feat: attachments loader and rethinking how importing commands work
  src/commands/misc/ping.ts
  src/commands/player/attachment.ts
  src/commands/player/skip.ts
  src/commands/player/stop.ts
  src/commands/player/youtube.ts
  src/index.ts
  src/lib/register.ts
  src/types/client.ts
  src/types/command.ts
Labels: enhancement

#8 fix: shorten `youtube` command to `yt`
  src/commands/player/youtube.ts
Labels: enhancement

#10 feat: added queue command, autocomplete fixes and node scripts
  package.json
  src/commands/player/attachment.ts
  src/commands/player/queue.ts
  src/commands/player/youtube.ts
  src/index.ts
Labels: bug, enhancement

#11 feat: make the reply of context menu private
  src/commands/player/attachment.ts
Labels: enhancement

#12 fix: new line on "upcoming" tracks embed
  src/commands/player/queue.ts
Labels: bug
